In [11]:
import numpy as np
from scipy.linalg import hilbert

In [4]:
A = np.eye(4) # 주대각 행렬을 4개 생성
A

Y = np.ones(4) #  모르겠음
Y

array([1., 1., 1., 1.])

In [5]:
#계수추정
np.linalg.solve(A, Y)

array([1., 1., 1., 1.])

In [6]:
A

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [8]:
A_new = A + 0.0001*np.eye(4)
A_new

array([[1.0001, 0.    , 0.    , 0.    ],
       [0.    , 1.0001, 0.    , 0.    ],
       [0.    , 0.    , 1.0001, 0.    ],
       [0.    , 0.    , 0.    , 1.0001]])

In [9]:
np.linalg.solve(A_new, Y)

array([0.99990001, 0.99990001, 0.99990001, 0.99990001])

In [10]:
# 조건수 확인
np.linalg.cond(A)

1.0

In [12]:
# 조건수가 클 때
# X 데이터
A = hilbert(4)
A

array([[1.        , 0.5       , 0.33333333, 0.25      ],
       [0.5       , 0.33333333, 0.25      , 0.2       ],
       [0.33333333, 0.25      , 0.2       , 0.16666667],
       [0.25      , 0.2       , 0.16666667, 0.14285714]])

In [14]:
Y = np.ones(4)
Y

array([1., 1., 1., 1.])

In [15]:
A_new = A + 0.0001*np.eye(4)
A_new

array([[1.0001    , 0.5       , 0.33333333, 0.25      ],
       [0.5       , 0.33343333, 0.25      , 0.2       ],
       [0.33333333, 0.25      , 0.2001    , 0.16666667],
       [0.25      , 0.2       , 0.16666667, 0.14295714]])

In [16]:
np.linalg.solve(A_new, Y)

array([ -0.58897672,  21.1225671 , -85.75912499,  78.45650825])

In [17]:
np.linalg.cond(A)

15513.73873892924